#!/bin/sh
#
# William Tisäter <william@defunct.cc>
#
# Nagios plugin for checking Slony-I lag status
# 

if [[ $# -ne 3 ]]
then
  echo "Usage: $0 <master> <cluster name> <dbname>"
  exit 2
fi

HOSTNAME=$1
CLUSTERNAME=$2
DBNAME=$3

TIME_BEHIND_WARN="600"
TIME_BEHIND_CRIT="3600"

nodelag=`/usr/bin/psql -h $HOSTNAME -c "select st_received, extract('epoch' from st_lag_time) from _${CLUSTERNAME}.sl_status ORDER BY st_lag_time DESC" -t $DBNAME`

if [ ! -n "$nodelag" ]; then
	echo "WARNING: Failed to get lag time"
	exit 1
fi

IFS=$'\n'
for node in $nodelag; do
	lag=$(echo $node | cut -d '|' -f 2 | cut -d '.' -f 1 | awk '{ print $1 }')
	nodeid=$(echo $node | cut -d '|' -f 1 | awk '{ print $1 }')
	nodename=$(/usr/bin/psql -h $HOSTNAME -c "select pa_conninfo from _${CLUSTERNAME}.sl_path where pa_server = $nodeid limit 1" -t $DBNAME | sed 's/.*host\=\([^ ]\+\) .*/\1/')

	if [ ! -n "$nodename" ]; then
		echo "WARNING: Failed to resolve node id"
		exit 1
	fi

	string="${string}($nodename $lag seconds) "

	if [ $lag -gt $TIME_BEHIND_CRIT ]; then
		critical=1
		continue
	fi

	if [ $lag -gt $TIME_BEHIND_WARN ]; then
		warning=1
		continue
	fi
done

if [ ! -z $critical ]; then
	echo "CRITICAL: $string"
	exit 2
elif [ ! -z $warning ]; then
	echo "WARNING: $string"
	exit 1
else
	echo "OK: $string"
	exit 0
fi
